config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'pages/about'

  get 'pages/rehabilitation'

  get 'pages/meuble'

  get 'pages/particulier'

  get 'pages/contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def rehabilitation
  end

  def meuble
  end

  def particulier
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qhome9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="about-page">
  <div class="about-content">
    <div class="image-about">
      <%= image_tag "quentin.jpg", class: "avatar-about" %>
    </div>
    <div class="description-about">
      <div class="title-about">
        Qui suis-je?
      </div>
      <div class="text-about">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni laborum omnis quod, optio nisi ducimus. Earum harum delectus accusamus ut accusantium asperiores tempora illo voluptas id? Cum autem delectus possimus.

        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum iure dignissimos sed, eius quibusdam praesentium nostrum exercitationem nemo cum neque distinctio tempora, ad laudantium quo quis quidem explicabo? Fuga, eveniet!
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-page">
  <div class="description-contact">
    <div class="title-contact">
      Thomas Quentin
    </div>
    <div class="text-contact">
       <div>
        <i class="fa fa-envelope-o"></i>
        quentinthomas@wanadoo.fr
      </div>
      <div>
        <i class="fa fa-phone"></i>
        +33 6 38 40 88 03
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-page">

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to pages_rehabilitation_path do %>
        <%= image_tag "bidassoa-003.png", class: "home-card" %>
        <% end %>
      </div>
       <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to pages_meuble_path do %>
        <%= image_tag "table1.jpg", class: "home-card"  %>
        <% end %>
        <span class= "home-card-description">
        Meubles d'inspiration fifties
        </span>
      </div>
       <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to pages_particulier_path do %>
        <%= image_tag "manel-2.jpg", class: "home-card" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/meuble.html.erb
<h1>Pages#meuble</h1>
<p>Find me in app/views/pages/meuble.html.erb</p>

app/views/pages/particulier.html.erb
<h1>Pages#particulier</h1>
<p>Find me in app/views/pages/particulier.html.erb</p>

app/views/pages/rehabilitation.html.erb
<div class="rehabilitation-page">

<div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4 swipebox">
        <%= image_tag "bidassoa-003.png", class: "pages-card" %>
          <div class="rehabilitation-picture">
          <%= image_tag "Bidassoa-001.jpg", class: "pages-card-small" %>
          <%= image_tag "Bidassoa-002.jpg", class: "pages-card-small" %>
          <%= image_tag "Bidassoa-004.jpg", class: "pages-card-small" %>
          <%= image_tag "Bidassoa-005.jpg", class: "pages-card-small" %>
          <%= image_tag "Bidassoa-006.jpg", class: "pages-card-small" %>
          <%= image_tag "Bidassoa-007.jpg", class: "pages-card-small" %>
          </div>
      </div>
       <div class="col-xs-12 col-sm-6 col-md-4">
        <%= image_tag "bluets1.jpg", class: "pages-card"  %>
        <span class= "pages-card-description">
        Meubles d'inspiration fifties
        </span>
      </div>
       <div class="col-xs-12 col-sm-6 col-md-4">
        <%= image_tag "republique1.jpg", class: "pages-card" %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-Qhome9">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-Qhome9-logo" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-Qhome9-right hidden-xs hidden-sm">


    <!-- Dropdown -->
    <div class="navbar-Qhome9-item">
      <div class="dropdown">
        <i class="fa fa-bars avatar dropdown-toggle" aria-hidden="true" id="navbar-Qhome9-menu" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-Qhome9-dropdown-menu">
          <li>
            <%link_to "Home", root_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
          <li>
            <%= link_to "About", pages_about_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
          <li>
            <%= link_to "Réhabilitation", pages_rehabilitation_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
          <li>
            <%= link_to "Meuble", pages_meuble_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
          <li>
            <%= link_to "Projets pour particuliers", pages_particulier_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
          <li>
            <%= link_to "Contact", pages_contact_path, class: "navbar-Qhome9-item navbar-Qhome9-link" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
  <!-- Dropdown appearing on mobile only -->
<!--   <div class="navbar-Qhome9-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-Qhome9-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div> -->